---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(vroom)

tweets <- vroom("/Users/d.murray/Documents/csaba_layout_pipeline/data/raw/hashed_tweet_keywords_for_ccnr.tsv", delim = "\t", col_types = c(id_str = "c", userid = "c", created_at = "_", text_keyword = "c"))

nodes <- read_csv("/Users/d.murray/Documents/csaba_layout_pipeline/data/derived/touchdesigner/panel_antivax-only_nodes.csv")

set.seed(1)
sample <- tweets %>%
  sample_n(1000)

# get amount of numfake
  # Get a weighted sample by the numfake

node_sample <- nodes %>%
  sample_n(1200, weight = numfake)


df <- tweets %>%
  inner_join(node_sample, by = c('userid')) %>%
  group_by(userid) %>%
  filter(row_number() < 5) %>%
  summarize(
    # Remove the pipe characters and marge keywords across group
    label = gsub("|", "", paste0(text_keyword, collapse = " "), fixed = T),
    # Then, select unique terms, then take the first 5 words of the aggregate list
    label = word(paste0(unique(unlist(str_split(label, " "))), collapse = " "), 1, 5),
    # get other data for each group
    x = first(x),
    y = first(y),
    z = first(z),
    numfake = first(numfake)
  ) %>%
  rowwise() %>%
  mutate(
    dist = sqrt(x^2 + y^2 + z^2),
    dirvec_x = x / dist,
    dirvec_y = y / dist,
    dirvec_z = z / dist,
  ) %>%
  select(x, y, z, dist, dirvec_x, dirvec_y, dirvec_z, label, numfake) %>%
  filter(!is.na(label))

df
write_csv(df, "~/Desktop/links.csv")
```


```{r}
df <- read_delim("/Users/d.murray/Documents/csaba_layout_pipeline/data/raw/user_misinformation_time_series_hashed.tsv", delim = "\t")

time.df <- df %>%
  #group_by(userid) %>%
  arrange(userid, year, month, day) %>%
  mutate(
    quarter = paste0("Q", ceiling(month / 3)),
  ) %>% 
  group_by(userid, year, quarter) %>%
  summarize(
    numfake = sum(num_fake, na.rm = T)
  ) %>%
  ungroup() %>%
  unite(time, year:quarter, sep = "-") %>%
  mutate(
    time = factor(time,
                  levels = c("2019-Q4", 
                             "2020-Q1", "2020-Q2", "2020-Q3", "2020-Q4",
                             "2021-Q1", "2021-Q2", "2021-Q3", "2021-Q4",
                             "2022-Q1", "2022-Q2", "2022-Q3", "2022-Q4")
                  )
  ) %>%
  pivot_wider(id_cols = userid, 
              names_from = time, 
              values_from = numfake, 
              values_fill = 0, 
              names_sort = T)



nodes <- read_csv("/Users/d.murray/Desktop/antivax-data/touchdesigner/panel_antivax-only_nodes.csv")
nodes.time <- nodes %>%
  left_join(time.df, by = "userid") %>%
  arrange(x) %>%
  slice(1:17280)

nodes.time

write_delim(nodes.time, "~/Desktop/panel_antivax-only_temporal.xyz", delim = "\t", col_names = F)
write_csv(nodes.time, "~/Desktop/panel_antivax-only_temporal.csv")
```


Now do it by month

```{r}


levels = c("2019-12",
                      paste0("2020-", str_pad(c(1:12), 2, pad = 0)),
                      paste0("2021-", str_pad(c(1:12), 2, pad = 0)),
                      paste0("2022-", str_pad(c(1:12), 2, pad = 0))
                    )
df <- read_delim("/Users/d.murray/Documents/csaba_layout_pipeline/data/raw/user_misinformation_time_series_hashed.tsv", delim = "\t")

time.df <- df %>%
  #group_by(userid) %>%
  arrange(userid, year, month, day) %>%
  mutate(month = str_pad(month, 2, pad = 0)) %>%
  group_by(userid, year, month) %>%
  summarize(
    numfake = sum(num_fake, na.rm = T)
  ) %>%
  ungroup() %>%
  unite(time, year:month, sep = "-") %>%
  mutate(
    time = factor(time, levels = levels)
  ) %>%
  pivot_wider(id_cols = userid, 
              names_from = time, 
              values_from = numfake, 
              values_fill = 0, 
              names_sort = T)

nodes <- read_csv("/Users/d.murray/Desktop/antivax-data/touchdesigner/panel_antivax-only_nodes.csv")
nodes.time <- nodes %>%
  left_join(time.df, by = "userid") %>%
  arrange(x) %>%
  slice(1:17280)

nodes.time


lapply(levels, function(period) {
  if (period %in% names(nodes.time)) {
    write_delim(nodes.time %>% select(x, y, z, numfake, verified, period), 
                paste0("~/Desktop/temporal-data/panel_antivax-only_temporal_", period, ".xyz"), 
                delim = "\t", 
                col_names = F)
  }
})


nodes.time %>% 
  select(x, y, z, numfake, verified, userid, "2020-12")

write_delim(nodes.time, "~/Desktop/panel_antivax-only_temporal.xyz", delim = "\t", col_names = F)
write_csv(nodes.time, "~/Desktop/panel_antivax-only_temporal.csv")

```